title: About Me
logo: /images/Ale_Pic.png
description: Over 16 years of combined experience in Production, Translation, Localization, Web Development, Quality Assurance, Project Management, and UX Design. 
show_downloads: false
theme: jekyll-theme-minimal
# google_analytics: [Your Google Analytics tracking ID]
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
